### ISSUE TITLE
ArgumentError: wrong number of arguments (given 2, expected 1) for respond_to_missing? in objects from other gems

### ISSUE THREAD

**Issue by davidrunger** [skryukov/typelizer#1]
Hello, and thank you for this wonderful new gem!

Frequently (though not totally reliably), when I run my test suite, an exception `ArgumentError: wrong number of arguments (given 2, expected 1)` occurs with a [stack trace like this](https://github.com/davidrunger/david_runger/actions/runs/10513097780/job/29127904630#step:11:215):

```
[...]/vendor/bundle/ruby/3.3.0/gems/isolator-1.1.0/lib/isolator/simple_hashie.rb:16:in `respond_to_missing?'
[...]/vendor/bundle/ruby/3.3.0/gems/typelizer-0.1.0/lib/typelizer/generator.rb:46:in `respond_to?'
[...]/vendor/bundle/ruby/3.3.0/gems/typelizer-0.1.0/lib/typelizer/generator.rb:46:in `block (2 levels) in read_serializers'
[...]/vendor/bundle/ruby/3.3.0/gems/isolator-1.1.0/lib/isolator/simple_hashie.rb:7:in `method_missing'
[...]
```

or [like this](https://github.com/davidrunger/david_runger/actions/runs/10513593089/job/29129520650#step:11:139):

```
[...]/vendor/bundle/ruby/3.3.0/gems/rollbar-3.5.2/lib/rollbar/configuration.rb:394:in `respond_to_missing?'
[...]/vendor/bundle/ruby/3.3.0/gems/typelizer-0.1.0/lib/typelizer/generator.rb:46:in `respond_to?'
[...]/vendor/bundle/ruby/3.3.0/gems/typelizer-0.1.0/lib/typelizer/generator.rb:46:in `block (2 levels) in read_serializers'
[...]/vendor/bundle/ruby/3.3.0/gems/rollbar-3.5.2/lib/rollbar/configuration.rb:378:in `initialize'
[...]
```

As we can see, these errors are occurring in `isolator` and in `rollbar`, respectively, and, indeed, I think that arguably the bug lies mostly with those gems (or other gems that might have the same flaw). Nevertheless, I think that `typelizer` (which comes just beneath those gems in the above stack traces) could avoid these exceptions, and I personally think that would be worth doing.

The fundamental issue is that it seems not to be safe to assume that any/every object can respond safely to `respond_to?`. Calling `respond_to?` will error if called with a method name that is not explicitly defined by the class in question and if that class implements a `respond_to_missing?` method that takes any number of arguments other than 2.

**Illustration:**

```rb
class Example
  def say_hi
    'Hello!'
  end

  # It's a problem that this method takes only one argument; it should take two.
  def respond_to_missing?(name)
    # some logic here...
  end
end

example = Example.new

# It's no problem to ask about a method that is explicitly defined.
example.respond_to?(:say_hi)
# => true

# It is a problem to ask about a method that is NOT explicitly defined.
example.respond_to?(:not_an_explicitly_defined_method)
# => raises ArgumentError (wrong number of arguments (given 2, expected 1))
```

We can see that, indeed, the mentioned gems do have `respond_to_missing?` methods that take only one argument (rather than two, as they should):

- `isolator`: https://github.com/palkan/isolator/blob/v1.1.0/lib/isolator/simple_hashie.rb#L16
- `rollbar`: https://github.com/rollbar/rollbar-gem/blob/v3.5.2/lib/rollbar/configuration.rb#L394

The exception occurs in those gems after being called from this line in `typelizer`: https://github.com/skryukov/typelizer/blob/v0.1.0/lib/typelizer/generator.rb#L46

```rb
next unless tp.self.respond_to?(:typelizer_interface) && !tp.self.send(:respond_to_missing?, :typelizer_interface, false)
```

The exception occurs in the first part of that conditional -- `tp.self.respond_to?(:typelizer_interface)` -- because of the fact that these other gems have classes where `respond_to_missing?` takes only one argument.

As I mentioned, arguably this isn't `typelizer`'s fault, since ideally it _should_ be safe to call `respond_to?` with any symbol argument on any object, but the reality is that it's not safe to do that with all objects created by other gems. It would be great if something could be changed in `typelizer` so that an exception won't occur in these conditions.

I'm not sure what exactly might be the best way to fix this. I think that something as simple as adding `ArgumentError` to the list of rescued exception classes [on L47 just below](https://github.com/skryukov/typelizer/blob/v0.1.0/lib/typelizer/generator.rb#L47) would solve the issue:

```rb
rescue ArgumentError, WeakRef::RefError
```

As I say, though, I'm not sure whether that's necessarily the overall best solution. But it certainly might be good enough.

Thanks again for the gem, and for reading this issue!

**Comment by skryukov** [comment]
The fix is available in [v0.1.1](https://github.com/skryukov/typelizer/compare/v0.1.0...v0.1.1). Thanks for your help @davidrunger 💕
