### ISSUE TITLE
Feature Request: Allowing a configutaion to support typescript's `verbatimModuleSyntax` module snytax

### ISSUE THREAD

**Issue by patvice** [skryukov/typelizer#15]
Hey @skryukov!

# Motivation
In our project, we have enabled verbatim module syntax configuration enabled in our tsconfig. This means we get linter errors around the export system because of how the type files are generated.

Example:

### What is generated
```ts
type Admin = {
  fullName: string;
}

export default Admin;
```

We currently get this error:

> An 'export default' must reference a value when 'verbatimModuleSyntax' is enabled, but 'Admin' only refers to a type.ts(1284)

### What ts would expect based on our config
```ts
type Admin = {
  fullName: string;
}

export type { Admin };
```

# Details
My first thought would be to add this as a configuration option at Typelize that would change the output to support a different exporting method. 

This would change both the index file and the generated type files. Looking at it, we'd probably mostly make the changes in the writer class and the `.erb` file that contains the generated type output.

# Additional info
I'm happy to take a crack at implementing this if you are okay with supporting it.

**Comment by skryukov** [comment]
Available in `0.2.0`, thanks @patvice!
